from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
path('',views.index1,name='index1'),
path('index',views.index,name='index'),
path('home/',views.home,name='home'),
path('base/',views.base,name='base'),
path('index/',views.index,name = 'index'),
path('Logins/',views.Logins,name='Logins'),
path('AdminLogin/',views.AdminLogin,name='AdminLogin'),
path('Logout/',views.Logout,name = 'Logout'),
path('ManageCompany/',views.ManageCompany,name = 'ManageCompany'),
path('AddCompany/',views.AddCompany,name = 'AddCompany'),
path('DisplayStudent/',views.DisplayStudent,name = 'DisplayStudent'),
path('Add_Off_Campus_Details/',views.Add_Off_Campus_Details,name='Add_Off_Campus_Details'),
path('View_Off_Campus_Details/',views.View_Off_Campus_Details,name='View_Off_Campus_Details'),
path('Placement_Statistics/',views.Placement_Statistics,name='Placement_Statistics'),
path('Visited_Companies/',views.Visited_Companies,name='Visited_Companies'),
path('Placement_Policies/',views.Placement_Policies,name='Placement_Policies'),
path('Student_Status/',views.Student_Status,name='Student_Status'),
path('Student_Login/',views.Student_Login,name='Student_Login'),
path('User_Registeration/',views.User_Registeration,name='User_Registeration'),
path('Educational_Details/',views.Educational_Details,name='Educational_Details'),
path('Previous_Details/',views.Previous_Details,name='Previous_Details'),
path('Contact_Details/',views.Contact_Details,name='Contact_Details'),
path('practise/',views.practise,name='practise'),
path('Profile/',views.Profile,name='Profile'),
path('Update/',views.Update,name='Update'),
path('College_Login/',views.College_Login,name='College_Login'),
path('COMPUTER_SCIENCE_AND_ENGINEERING/',views.COMPUTER_SCIENCE_AND_ENGINEERING,name='COMPUTER_SCIENCE_AND_ENGINEERING'),
path('view/<int:id>',views.view,name='view'),
path('Manage_Company/',views.Manage_Company,name='Manage_Company'),
path('Change_Password/',views.Change_Password,name='Change_Password'),
#path('pie_chart/', views.pie_chart, name='pie_chart'),
path('Eligible_Company_List/',views.Eligible_Company_List,name='Eligible_Company_List'),
path('ELECTRONICS_AND_COMMUNICATION_ENGINEERING/',views.ELECTRONICS_AND_COMMUNICATION_ENGINEERING,name='ELECTRONICS_AND_COMMUNICATION_ENGINEERING'),
path('INFORMATION_SCIENCE_AND_ENGINEERING/',views.INFORMATION_SCIENCE_AND_ENGINEERING,name='INFORMATION_SCIENCE_AND_ENGINEERING'),
path('OffCampus_User/',views.OffCampus_User,name='OffCampus_User'),
path('Placements_User/',views.Placements_User,name='Placements_User'),
path('ApplyJob/',views.ApplyJob,name='ApplyJob'),
path('EditCompany/<int:id>',views.EditCompany,name='EditCompany'),
path('DeleteComp/<int:id>',views.DeleteComp,name = 'DeleteComp'),
path('Placement_Admin/',views.Placement_Admin,name = 'Placement_Admin'),
path('User_AddOffCampus/',views.User_AddOffCampus,name = 'User_AddOffCampus'),
path('view1/<int:id>',views.view1,name='view1'),
path('User_OffCampus/',views.User_OffCampus,name = 'User_OffCampus'),
path('DisplayPlacements/',views.DisplayPlacements,name = 'DisplayPlacements'),
path('pie_chart/',views.pie_chart,name = 'pie_chart'),
path('AddPlaced_status/',views.AddPlaced_status,name = 'AddPlaced_status'),
path('placed_bar/',views.placed_bar,name = 'placed_bar'),
path('Student_ofers/',views.Student_ofers,name = 'Student_ofers'),
path('All_Companies/',views.All_Companies,name = 'All_Companies'),
path('CIVIL_Display/',views.CIVIL_Display,name = 'CIVIL_Display'),
path('CSI_Display/',views.CSI_Display,name = 'CSI_Display'),

path('Placed/',views.Placed,name = 'Placed'),
path('ECE_Display/',views.ECE_Display,name = 'ECE_Display'),
path('Display_Placed/',views.Display_Placed,name = 'Display_Placed'),
path('EEE_Display/',views.EEE_Display,name = 'EEE_Display'),
path('IP_Display/',views.IP_Display,name = 'IP_Display'),
path('IS_Display/',views.IS_Display,name = 'IS_Display'),
path('MECH_Display/',views.MECH_Display,name = 'MECH_Display'),
path('Companies/',views.Companies,name = 'Companies'),
path('Forecasting/',views.Forecasting,name = 'Forecasting'),
path('news/',views.news,name = 'news'),
path('OffCampus_Del/<int:id>',views.OffCampus_Del,name = 'OffCampus_Del'),
path('OffCampus_edit/<int:id>',views.OffCampus_edit,name = 'OffCampus_edit'),
]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)