# Generated by Django 3.1.3 on 2022-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'admindata',
            },
        ),
        migrations.CreateModel(
            name='CollegeLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'CollegeLogin',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(default=None, max_length=100)),
                ('Package', models.CharField(default=None, max_length=100)),
                ('File', models.FileField(default=None, upload_to='media')),
                ('Pre_Placement', models.DateTimeField()),
                ('Test_Date', models.DateTimeField()),
                ('Interview_Date', models.DateTimeField()),
                ('Additional_Information', models.CharField(default=None, max_length=100)),
                ('CGPA', models.CharField(default=None, max_length=100)),
                ('CSl', models.CharField(blank=True, default=None, max_length=100)),
                ('IS', models.CharField(blank=True, default=None, max_length=100)),
                ('ECE', models.CharField(blank=True, default=None, max_length=100)),
                ('EEE', models.CharField(blank=True, default=None, max_length=100)),
                ('MECH', models.CharField(blank=True, default=None, max_length=100)),
                ('IP', models.CharField(blank=True, default=None, max_length=100)),
                ('CIVIL', models.CharField(blank=True, default=None, max_length=100)),
                ('ALL_BRANCHES', models.CharField(blank=True, default=None, max_length=100)),
                ('OTHERS', models.CharField(blank=True, default=None, max_length=100)),
                ('CATEGORY', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'db_table': 'CompanyDetails',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(default=None, max_length=100)),
                ('Package', models.CharField(default=None, max_length=100)),
                ('File', models.FileField(default=None, upload_to='media')),
                ('Pre_Placement', models.DateTimeField()),
                ('Test_Date', models.DateTimeField()),
                ('Interview_Date', models.DateTimeField()),
                ('Additional_Information', models.CharField(default=None, max_length=100)),
                ('CGPA', models.IntegerField(default=None)),
                ('Stream', models.TextField(default=None, max_length=100)),
                ('OTHERS', models.CharField(blank=True, default=None, max_length=100)),
                ('CATEGORY', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'db_table': 'CompanyDetails11',
            },
        ),
        migrations.CreateModel(
            name='offCampusPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(default=None, max_length=100)),
                ('CompanyName', models.CharField(default=None, max_length=100)),
                ('package', models.CharField(default=None, max_length=100)),
                ('proof', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'offCampusPlaced',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('uname', models.CharField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('USN', models.CharField(default=None, max_length=100, null=True)),
                ('Date_of_Birth', models.CharField(default=None, max_length=100, null=True)),
                ('Gender', models.CharField(default=None, max_length=100, null=True)),
                ('Category', models.CharField(default=None, max_length=100, null=True)),
                ('Mode_of_admission', models.CharField(default=None, max_length=100, null=True)),
                ('Engineering_branch', models.CharField(default=None, max_length=100, null=True)),
                ('Section', models.CharField(default=None, max_length=100, null=True)),
                ('Year_of_joining', models.IntegerField(default=None, null=True)),
                ('Year_of_passing', models.IntegerField(default=None, null=True)),
                ('first_sem_SGPA', models.IntegerField(default=None, null=True)),
                ('first_sem_percentage', models.IntegerField(default=None, null=True)),
                ('second_sem_SGPA', models.IntegerField(default=None, null=True)),
                ('second_sem_percentage', models.IntegerField(default=None, null=True)),
                ('third_sem_SGPA', models.IntegerField(default=None, null=True)),
                ('third_sem_percentage', models.IntegerField(default=None, null=True)),
                ('fourth_sem_SGPA', models.IntegerField(default=None, null=True)),
                ('fourth_sem_percentage', models.IntegerField(default=None, null=True)),
                ('fifth_sem_SGPA', models.IntegerField(default=None, null=True)),
                ('fifth_sem_percentage', models.IntegerField(default=None, null=True)),
                ('Total_CGPA', models.IntegerField(default=None, null=True)),
                ('Total_CGPA_per', models.IntegerField(default=None, null=True)),
                ('TOTAL_CREDITS_EARNED_UPTO_5TH_SEMESTER', models.IntegerField(default=None, null=True)),
                ('NUMBER_OF_SUBJECTS_CLEARED_IN_MUTE', models.IntegerField(default=None, null=True)),
                ('CURRENT_ARREARS', models.IntegerField(default=None, null=True)),
                ('tenth_SSLC_percentage', models.IntegerField(default=None, null=True)),
                ('tenth_sslc_board', models.IntegerField(default=None, null=True)),
                ('Name_of_institution_studied_in_10th_sslc', models.CharField(default=None, max_length=100, null=True)),
                ('tenth_sslc_qualified_year', models.IntegerField(default=None, null=True)),
                ('twelveth_PUC_percentage', models.IntegerField(default=None, null=True)),
                ('twelveth_PUC_board', models.IntegerField(default=None, null=True)),
                ('Name_of_the_institution_studied_12th_Puc', models.CharField(default=None, max_length=100, null=True)),
                ('twelveth_PUC_qualified_year', models.IntegerField(default=None, null=True)),
                ('Diploma_percentage', models.IntegerField(default=None, null=True)),
                ('Diploma_CET_percentage', models.IntegerField(default=None, null=True)),
                ('Name_of_the_institution_studied_diploma', models.CharField(default=None, max_length=100, null=True)),
                ('Diploma_qualified_year', models.IntegerField(default=None, null=True)),
                ('contact_number', models.CharField(default=None, max_length=100, null=True)),
                ('LANDLINE_NUMBER', models.CharField(default=None, max_length=100, null=True)),
                ('PARENTS_NUMBER', models.CharField(default=None, max_length=100, null=True)),
                ('Alternate_contact_number', models.CharField(default=None, max_length=100, null=True)),
                ('EMAIL_ID', models.EmailField(default=None, max_length=100, null=True)),
                ('College_mail', models.EmailField(default=None, max_length=100, null=True)),
                ('CURRENT_ADDRESS', models.CharField(default=None, max_length=100, null=True)),
                ('PERMANENT_ADDRESS', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Student_Details',
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(default=None, max_length=100, null=True)),
                ('Student_name', models.CharField(default=None, max_length=100, null=True)),
                ('Company_id', models.CharField(default=None, max_length=100, null=True)),
                ('Company_name', models.CharField(default=None, max_length=100, null=True)),
                ('Status', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'StudentApplication',
            },
        ),
    ]
