# Generated by Django 3.1.3 on 2022-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0002_auto_20220527_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='Select_status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
