# Generated by Django 3.2.12 on 2022-05-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0004_auto_20220527_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsseroffCampusPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(default=None, max_length=100)),
                ('CompanyName', models.CharField(default=None, max_length=100)),
                ('package', models.CharField(default=None, max_length=100)),
                ('proof', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'UsseroffCampusPlaced',
            },
        ),
    ]
