# Generated by Django 3.1.3 on 2022-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0005_usseroffcampusplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='Student_USN',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
