# Generated by Django 3.1.3 on 2022-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0006_studentapplication_student_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='Student_Category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
