# Generated by Django 3.1.3 on 2022-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0007_studentapplication_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails11',
            name='Category_Number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
