# Generated by Django 3.1.3 on 2022-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0008_companydetails11_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails11',
            name='CGPA',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
