# Generated by Django 3.1.3 on 2022-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0009_auto_20220614_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Diploma_CET_percentage',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Diploma_percentage',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Diploma_qualified_year',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
