# Generated by Django 3.1.3 on 2022-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0010_auto_20220627_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='tenth_sslc_board',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
