# Generated by Django 3.1.3 on 2022-06-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCampusPlacement', '0011_auto_20220627_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='twelveth_PUC_board',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
